[versions]
agp = "8.13.0"
api = "13.1.5"
casclientAndroid = "3.4.1"
fastjson2 = "2.0.57"
glide = "4.11.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
lifecycleLivedataKtx = "2.6.1"
lifecycleViewmodelKtx = "2.6.1"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
legacySupportV4 = "1.0.0"
activity = "1.8.0"
okhttp = "4.12.0"
annotation = "1.6.0"
kotlin = "2.0.0"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.04.01"
preference = "1.2.0"
wechatSdkAndroid = "6.8.34"
workRuntime = "2.10.4"
materialPreference = "2.0.0"
materialVersion = "2.7.2"

[libraries]
api = { module = "dev.rikka.shizuku:api", version.ref = "api" }
casclient-android = { module = "org.jasig.cas.client.android:casclient-android", version.ref = "casclientAndroid" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version = "2.0.59.android8" }
glide = { module = "com.github.bumptech.glide:glide", version = "5.0.5" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
material = { group = "com.google.android.material", name = "material", version = "1.14.0-alpha02" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.6.2" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.6.2" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.2.1" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.6.2" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
provider = { module = "dev.rikka.shizuku:provider", version.ref = "api" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.6.6" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
wechat-sdk-android = { module = "com.tencent.mm.opensdk:wechat-sdk-android", version.ref = "wechatSdkAndroid" }
work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "workRuntime" }
material-preference = { group = "dev.rikka.rikkax.material", name = "material-preference", version.ref = "materialPreference" }
dev-material = { group = "dev.rikka.rikkax.material", name = "material", version.ref = "materialVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

